import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowRight, BookOpenText, CheckCircle2, Clock3, DatabaseZap, Radar, SlidersHorizontal } from "lucide-react";
import { Link } from "wouter";

const statusStyle: Record<string, string> = { success: "status-success", partial: "status-partial", failed: "status-failed", running: "status-running" }; const statusLabel: Record<string, string> = { success: "成功", partial: "一部完了", failed: "失敗", running: "実行中" };
function formatDate(value: Date | string | null | undefined) { if (!value) return "—"; return new Date(value).toLocaleString("ja-JP", { dateStyle: "medium", timeStyle: "short" }); }

export default function DashboardPage() {
  const metrics = trpc.dashboard.metrics.useQuery(); const recentRuns = trpc.dashboard.recentRuns.useQuery({ limit: 6 }); const latest = metrics.data?.latestRun?.run; const failures = (recentRuns.data ?? []).reduce((total, item) => total + item.run.failedItems, 0);
  const metricCards = [{ label: "有効な収集条件", value: metrics.data?.activeRules, caption: "バックグラウンドで監視中", icon: Radar, tone: "indigo" }, { label: "翻訳済み知識", value: metrics.data?.processedArticles, caption: "検索可能な記事", icon: BookOpenText, tone: "gold" }, { label: "直近の実行", value: latest ? statusLabel[latest.status] : "未実行", caption: latest ? formatDate(latest.completedAt ?? latest.startedAt) : "収集条件を追加してください", icon: Activity, tone: "rose" }];
  return <div className="space-y-8 page-enter"><section className="hero-panel"><div className="hero-grid" /><div className="relative z-10 max-w-2xl"><p className="eyebrow text-primary-foreground/70">CURATED INTELLIGENCE</p><h1>AIの変化を、<em>知識の地図</em>に。</h1><p>Redditの会話を日本語で読み解き、必要なときに再発見できる静かなリサーチ空間です。</p></div><div className="hero-actions relative z-10"><Link href="/rules"><Button className="hero-button"><SlidersHorizontal size={16} />収集条件を設定</Button></Link><Link href="/knowledge"><Button variant="outline" className="hero-outline">知識を検索 <ArrowRight size={15} /></Button></Link></div></section>
    <section className="metrics-grid">{metricCards.map(card => <article className="metric-card" key={card.label}><div className={`metric-icon ${card.tone}`}><card.icon size={19} /></div><p>{card.label}</p>{metrics.isLoading ? <Skeleton className="mt-3 h-9 w-20" /> : <strong>{card.value ?? 0}</strong>}<small>{card.caption}</small></article>)}</section>
    <section className="content-card run-card"><div className="section-heading"><div><p className="eyebrow">COLLECTION ACTIVITY</p><h2>実行履歴</h2></div><div className="failure-summary">{failures > 0 ? <><AlertTriangle size={15} />直近の失敗 {failures} 件</> : <><CheckCircle2 size={15} />直近のエラーなし</>}</div></div>{recentRuns.isLoading ? <div className="space-y-3 py-3">{Array.from({ length: 3 }).map((_, index) => <Skeleton className="h-16 w-full" key={index} />)}</div> : recentRuns.data?.length ? <div className="run-list">{recentRuns.data.map(({ run, ruleName }) => <div className="run-row" key={run.id}><div className="run-rule"><span className={`run-pulse ${run.status === "failed" ? "pulse-failed" : ""}`} /><div><strong>{ruleName}</strong><small><Clock3 size={12} />{formatDate(run.startedAt)}</small>{run.errorMessage && <span className="run-error"><AlertTriangle size={12} />{run.errorMessage}</span>}</div></div><div className="run-numbers"><span>{run.processedItems} 件処理</span><span>{run.fetchedPosts} 投稿</span>{run.failedItems > 0 && <span className="error-count">{run.failedItems} 件失敗</span>}</div><Badge className={`status-badge ${statusStyle[run.status]}`}>{statusLabel[run.status]}</Badge></div>)}</div> : <div className="empty-inline"><DatabaseZap size={22} /><p>まだ実行履歴はありません。収集条件を保存し、Reddit認証情報を設定するとここに記録されます。</p></div>}</section>
  </div>;
}
